name: Test install from Github

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install package from Github
      run: |
        python -m pip install https://github.com/messa/blockcopy/archive/refs/heads/main.zip
        
    - name: Run --help
      run: |
        blockcopy --help
