name: Test install from Github

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install package from Github
      run: |
        python -m pip install https://github.com/messa/blockcopy/archive/refs/heads/main.zip
        
    - name: Run --help
      run: |
        blockcopy --help

    - name: Run end-to-end test
      run: |
        dd if=/dev/urandom bs=1M count=32 of=test_src
        dd if=/dev/urandom bs=1M count=32 of=test_dst
        sha1sum test_src | tee test_src.sha1
        blockcopy checksum test_dst | \
          blockcopy retrieve test_src | \
          blockcopy save test_dst
        cmp test_src test_dst
        sha1sum -c test_src.sha1
